### ISSUE TITLE
Android Compilation: package im.shimo.react.cookie does not exist

### ISSUE THREAD

**Issue by Russdaddy** [joeferraro/react-native-cookies#57]
I get the following error when trying to run react-native run-android, iOS seems to work fine.

```
error: package im.shimo.react.cookie does not exist
import im.shimo.react.cookie.CookieManagerPackage;

error: cannot find symbol
            new CookieManagerPackage()
                ^
  symbol: class CookieManagerPackage
2 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

```

**Comment by Sean-Brown** [comment]
I'm getting the same error, how did you resolve it?

**Comment by Sean-Brown** [comment]
@tangzhirong I don't exactly remember but usually this issue happens because the `react-native link` command is buggy and adds duplicate entries to the following files:

- ./android/settings.gradle
- ./android/app/build.gradle

Check for duplicates in these files, if there are duplicates then eliminate the duplicates. If there are no duplicates then try running `react-native link` again, then remove the duplicates after running that command. Then delete the `./android/app/build/` folder, and then try running `react-native run-android` again and see if that solves your issue.
